insert into `routes` VALUES(4, 'boulder', 'V3', 1, 'Rec Finals', '10/15/13', 'Chloe Jelenc, David Foley', 'none', 'none', 'penguin', 'Rec Finals, V3, Rope 1', 'foleyda');
insert into `routes` VALUES(110, 'boulder', 'V4', 9, 'Alice in Wonderland', '01/19/14', 'Golden Wrench', 'hotpink', 'none', 'none', 'Alice in Wonderland, V4, Rope 9', 'jonbloom');
insert into `routes` VALUES(93, 'boulder', 'V3', 10, 'Who Put Dat Der??', '01/09/14', 'Andrew Herring', 'none', 'none', 'none', 'Who Put Dat Der??, V3, Rope 10', 'jonbloom');
insert into `routes` VALUES(104, 'boulder', 'V2', 5, 'Make Me Change The Tape', '01/19/14', 'Golden Wrench', 'gray', 'none', 'none', 'Make Me Change The Tape, V2, Rope 5', 'jonbloom');
insert into `routes` VALUES(8, 'boulder', 'V4', 3, 'The Apoplectic Rage of Nicolas Cage', '10/20/13', 'Andrew Herring', 'hotpink', 'none', 'black', 'The Apoplectic Rage of Nicolas Cage, V4, Rope 3', 'herringa');
insert into `routes` VALUES(109, 'toprope', '10a', 8, 'Pockets N'' StuF', '01/19/14', 'Golden Wrench', 'black', 'none', 'none', 'Pockets N'' StuF, 5.10a, Rope 8', 'jonbloom');
insert into `routes` VALUES(108, 'toprope', '9', 8, 'It''s a 5.9?', '01/19/14', 'Golden Wrench', 'white', 'none', 'none', 'It''s a 5.9?, 5.9, Rope 8', 'jonbloom');
insert into `routes` VALUES(15, 'boulder', 'V1', 1, 'Like Buttah', '10/20/13', 'Andrew Herring', 'none', 'none', 'green', 'Like Buttah, V1, Rope 1', 'herringa');
insert into `routes` VALUES(14, 'boulder', 'V0', 6, 'Little Pink Elephants', '10/20/13', 'Andrew Herring, Kelsey Evans', 'pink', 'none', 'hotpink', 'Little Pink Elephants, V0, Rope 6', 'herringa');
insert into `routes` VALUES(16, 'boulder', 'V1', 7, 'Half Dome', '10/19/13', 'Joe Bitely', 'none', 'none', 'lightgreen', 'Half Dome, V1, Rope 7', 'herringa');
insert into `routes` VALUES(17, 'boulder', 'V3', 1, 'Up Yours', '10/19/13', 'Jordan Campbell', 'none', 'none', 'blue', 'Up Yours, V3, Rope 1', 'mcgeema');
insert into `routes` VALUES(18, 'boulder', 'V9', 3, '360', '10/19/13', 'Jake Jensen', 'lightgreen', 'none', 'purple', '360, V9, Rope 3', 'herringa');
insert into `routes` VALUES(20, 'boulder', 'V0', 11, '60', '10/19/13', 'Joe Bitely', 'white', 'none', 'pink', '60, V0, Rope 11', 'mcgeema');
insert into `routes` VALUES(21, 'boulder', 'V8', 4, '340', '10/19/13', 'Guy Gordon', 'none', 'none', 'purple', '340, V8, Rope 4', 'herringa');
insert into `routes` VALUES(22, 'boulder', 'V8', 2, '350', '10/19/13', 'Kyle Stark', 'none', 'none', 'purple', '350, V8, Rope 2', 'herringa');
insert into `routes` VALUES(48, 'boulder', 'V2', 9, 'Green Machine', '10/19/13', 'Nick Chinzi', 'none', 'none', 'none', 'Green Machine, V2, Rope 9', 'herringa');
insert into `routes` VALUES(25, 'boulder', 'V7', 5, '330', '10/19/13', 'Jake Jensen', 'none', 'none', 'white', '330, V7, Rope 5', 'herringa');
insert into `routes` VALUES(70, 'boulder', 'V1', 4, 'Santa Farts', '11/19/13', 'Unknown', 'red', 'none', 'green', 'Santa Farts, V1, Rope 4', 'herringa');
insert into `routes` VALUES(97, 'toprope', '10a', 1, 'A Game of Risk', '01/19/14', 'Golden Wrench', 'yellow', 'none', 'none', 'A Game of Risk, 5.10a, Rope 1', 'jonbloom');
insert into `routes` VALUES(28, 'boulder', 'V6', 1, '280', '10/19/13', 'Rob Veldman', 'none', 'none', 'yellow', '280, V6, Rope 1', 'herringa');
insert into `routes` VALUES(29, 'boulder', 'V6', 4, '300', '10/19/13', 'Rob Veldman', 'none', 'none', 'yellow', '300, V6, Rope 4', 'jonbloom');
insert into `routes` VALUES(33, 'boulder', 'V1', 4, '120', '10/19/13', 'Kelsey Evans', 'none', 'none', 'lightgreen', '120, V1, Rope 4', 'mcgeema');
insert into `routes` VALUES(31, 'boulder', 'V5', 5, 'Pumpkinception', '10/19/13', 'Jordan Campbell', 'purple', 'none', 'red', 'Pumpkinception, V5, Rope 5', 'herringa');
insert into `routes` VALUES(46, 'toprope', '9', 2, 'Orangellow', '10/22/13', 'Jon Bloom', 'yellow', 'none', 'none', 'Orangellow, 5.9, Rope 2', 'jonbloom');
insert into `routes` VALUES(34, 'toprope', '10a', 2, 'Top Rope Route 2', '10/20/13', 'Dan Bologna', 'orange', 'none', 'blue', 'Top Rope Route 2, 5.10a, Rope 2', 'herringa');
insert into `routes` VALUES(35, 'boulder', 'V1', 0, '130', '10/19/13', 'Chloe Jelenc', 'pink', 'none', 'lightgreen', '130, V1, Rope ', 'mcgeema');
insert into `routes` VALUES(36, 'boulder', 'V1', 10, '100', '10/19/13', 'Becca Reyhl', 'pink', 'none', 'green', '100, V1, Rope 10', 'mcgeema');
insert into `routes` VALUES(98, 'boulder', 'V3', 1, 'Golden Wrench 11', '01/19/14', 'Golden Wrench', 'red', 'none', 'none', 'Golden Wrench 11, V3, Rope 1', 'jonbloom');
insert into `routes` VALUES(99, 'boulder', 'V2', 2, 'Half and Half', '01/19/14', 'Golden Wrench', 'hotpink', 'none', 'none', 'Half and Half, V2, Rope 2', 'jonbloom');
insert into `routes` VALUES(45, 'toprope', '8', 1, 'Smoky Ghosts', '10/22/13', 'Dan Bologna', 'none', 'none', 'lightgreen', 'Smoky Ghosts, 5.8, Rope 1', 'herringa');
insert into `routes` VALUES(43, 'toprope', '8', 8, 'Mount Watkins', '10/22/13', 'Joe Bitely', 'teal', 'none', 'green', 'Mount Watkins, 5.8, Rope 8', 'herringa');
insert into `routes` VALUES(47, 'boulder', 'V0', 9, 'Noo Bladder', '10/19/13', 'Nick Chinzi', 'none', 'none', 'none', 'Noo Bladder, V0, Rope 9', 'jonbloom');
insert into `routes` VALUES(52, 'toprope', '10a', 7, 'Patty The Possum', '10/22/13', 'Dan Bologna', 'lime', 'none', 'blue', 'Patty The Possum, 5.10a, Rope 7', 'herringa');
insert into `routes` VALUES(103, 'toprope', '10b', 4, '24-Karats', '01/19/14', 'Golden Wrench', 'blue', 'none', 'lightblue', '24-Karats, 5.10b, Rope 4', 'jonbloom');
insert into `routes` VALUES(57, 'toprope', '9', 7, 'Free Hugs', '10/23/13', 'Jon Bloom', 'blue', 'none', 'none', 'Free Hugs, 5.9, Rope 7', 'jonbloom');
insert into `routes` VALUES(86, 'toprope', '10c', 2, 'Hand Tossed', '11/25/13', 'Aaron Herndon', 'none', 'none', 'none', 'Hand Tossed, 5.10c, Rope 2', 'reyhlr');
insert into `routes` VALUES(100, 'boulder', 'V1', 3, 'The Sexy Carpenter', '01/19/14', 'Golden Wrench', 'none', 'none', 'none', 'The Sexy Carpenter, V1, Rope 3', 'jonbloom');
insert into `routes` VALUES(58, 'toprope', '9', 3, 'Betty Nugs', '10/29/13', 'Jordan Campbell', 'lightgreen', 'none', 'none', 'Betty Nugs, 5.9, Rope 3', 'herringa');
insert into `routes` VALUES(59, 'toprope', '10d', 7, 'Defibrilation', '10/29/13', 'Andrew Herring', 'none', 'none', 'none', 'Defibrilation, 5.10d, Rope 7', 'herringa');
insert into `routes` VALUES(112, 'toprope', '8', 10, 'In the Cave', '01/19/14', 'Joe Bitely', 'saddlebrown', 'none', 'none', 'In the Cave, 5.8, Rope 10', 'foleyda');
insert into `routes` VALUES(63, 'boulder', 'V3', 5, '210', '10/18/13', 'Becca Reyhl', 'none', 'none', 'lightblue', '210, V3, Rope 5', 'evankels');
insert into `routes` VALUES(62, 'boulder', 'V3', 6, 'Inspector Gadget', '10/18/13', 'Joe Bitely', 'none', 'none', 'none', 'Inspector Gadget, V3, Rope 6', 'evankels');
insert into `routes` VALUES(65, 'toprope', '10d', 4, 'Even I Got Pumped', '10/31/13', 'Aaron Herndon', 'blue', 'none', 'none', 'Even I Got Pumped, 5.10d, Rope 4', 'foleyda');
insert into `routes` VALUES(66, 'toprope', '11a', 4, 'Strangely Reminiscent', '11/03/13', 'Becca Reyhl', 'white', 'none', 'none', 'Strangely Reminiscent, 5.11a, Rope 4', 'foleyda');
insert into `routes` VALUES(111, 'toprope', '9', 10, 'Make-Out Point', '01/19/14', 'Golden Wrench', 'lime', 'none', 'none', 'Make-Out Point, 5.9, Rope 10', 'jonbloom');
insert into `routes` VALUES(102, 'boulder', 'V0', 4, 'My Valentine', '01/20/14', 'Joe Bitely', 'red', 'none', 'none', 'My Valentine, V0, Rope 4', 'foleyda');
insert into `routes` VALUES(68, 'toprope', '10a', 3, 'Trashin'' The Camp', '11/13/13', 'Andrew Herring', 'none', 'none', 'teal', 'Trashin'' The Camp, 5.10a, Rope 3', 'herringa');
insert into `routes` VALUES(69, 'boulder', 'V7', 10, '310', '10/19/13', 'Rob Veldman', 'none', 'none', 'none', '310, V7, Rope 10', 'reyhlr');
insert into `routes` VALUES(71, 'toprope', '12b', 4, 'Venga, Venga!!', '11/24/13', 'Andrew Herring', 'purple', 'none', 'white', 'Venga, Venga!!, 5.12b, Rope 4', 'herringa');
insert into `routes` VALUES(72, 'toprope', '9', 1, 'Turkey Baster', '11/26/13', 'Dan Bologna', 'none', 'none', 'none', 'Turkey Baster, 5.9, Rope 1', 'reyhlr');
insert into `routes` VALUES(76, 'boulder', 'V2', 3, 'Ron Burgandy?', '11/22/13', 'Climbing Class', 'teal', 'none', 'none', 'Ron Burgandy?, V2, Rope 3', 'herringa');
insert into `routes` VALUES(101, 'toprope', '9', 3, 'It Gets Better (Or Not)', '01/19/14', 'Golden Wrench', 'none', 'none', 'none', 'It Gets Better (Or Not), 5.9, Rope 3', 'jonbloom');
insert into `routes` VALUES(75, 'toprope', '9', 3, 'Jolly Old Sent Nick', '12/05/13', 'Joe Bitely', 'purple', 'none', 'none', 'Jolly Old Sent Nick, 5.9, Rope 3', 'herringa');
insert into `routes` VALUES(77, 'boulder', 'V1', 7, 'Santa''s Crack', '11/20/13', 'Climbing Class', 'red', 'none', 'none', 'Santa''s Crack, V1, Rope 7', 'herringa');
insert into `routes` VALUES(113, 'toprope', '10b', 6, '6 Minutes to Spare', '01/19/14', 'Golden Wrench', 'black', 'none', 'lightblue', '6 Minutes to Spare, 5.10b, Rope 6', 'jonbloom');
insert into `routes` VALUES(106, 'boulder', 'V4', 6, 'Box', '01/19/14', 'Golden Wrench', 'lime', 'none', 'none', 'Box, V4, Rope 6', 'jonbloom');
insert into `routes` VALUES(107, 'boulder', 'V3', 8, 'The Blue Power Ranger', '01/19/14', 'Golden Wrench', 'white', 'none', 'none', 'The Blue Power Ranger, V3, Rope 8', 'jonbloom');
insert into `routes` VALUES(80, 'toprope', '10c', 3, 'Thin''N''Crispy', '11/25/13', 'Dan Bologna', 'lightgreen', 'none', 'none', 'Thin''N''Crispy, 5.10c, Rope 3', 'herringa');
insert into `routes` VALUES(81, 'boulder', 'V0', 1, 'Banana Split', '11/20/13', 'Climbing Class', 'yellow', 'none', 'lightgreen', 'Banana Split, V0, Rope 1', 'herringa');
insert into `routes` VALUES(96, 'toprope', '7', 11, 'Bask in the Glow', '01/15/14', 'Jon Bloom', 'none', 'none', 'none', 'Bask in the Glow, 5.7, Rope 11', 'jonbloom');
insert into `routes` VALUES(83, 'toprope', '9', 4, 'Best Route on Campus', '10/22/13', 'Joe Bitely', 'none', 'none', 'none', 'Best Route on Campus, 5.9, Rope 4', 'reyhlr');
insert into `routes` VALUES(87, 'toprope', '7', 9, 'HIPHOPOPOTOMUS', '12/09/13', 'Cassie Miles', 'black', 'none', 'none', 'HIPHOPOPOTOMUS, 5.7, Rope 9', 'herringa');
insert into `routes` VALUES(88, 'toprope', '11a', 11, 'Down The Rabbit Hole', '12/10/13', 'Andrew Herring', 'none', 'none', 'none', 'Down The Rabbit Hole, 5.11a, Rope 11', 'jonbloom');
insert into `routes` VALUES(89, 'toprope', '11a', 6, 'Elf''s Lament', '12/12/13', 'Nick Anders', 'none', 'none', 'none', 'Elf''s Lament, 5.11a, Rope 6', 'herringa');
insert into `routes` VALUES(90, 'toprope', '10d', 2, 'Wahoooo', '01/04/14', 'Aaron Tyner', 'lightgreen', 'white', 'none', 'Wahoooo, 5.10d, Rope 2', 'foleyda');
insert into `routes` VALUES(91, 'boulder', 'V2', 0, 'Squiggle', '01/04/14', 'Eric Carlson', 'lightgreen', 'none', 'none', 'Squiggle, V2, Rope ', 'foleyda');
insert into `routes` VALUES(92, 'toprope', '10b', 5, 'Dexter', '01/04/14', 'Eric Carlson', 'hotpink', 'none', 'none', 'Dexter, 5.10b, Rope 5', 'foleyda');
insert into `routes` VALUES(94, 'boulder', 'V3', 4, 'Slightly Inappropiate', '01/13/14', 'Andrew Herring', 'none', 'none', 'none', 'Slightly Inappropiate, V3, Rope 4', 'jonbloom');
insert into `routes` VALUES(95, 'boulder', 'V7', 11, 'Kyle''s Route?', '01/10/14', 'Kyle Stark', 'black', 'none', 'none', 'Kyle''s Route?, V7, Rope 11', 'foleyda');
